/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.Painel;
import observer.painel.EstacaoClimatica;
import observer.painel.EstatisticaClimaObserver;
import observer.painel.MaximasMinimasObserver;
import observer.painel.PainelClimaObserver;
import presenter.DadosClimaticosPresenter;

/**
 *
 * @author rauni
 */
public class ViewDadosClima extends javax.swing.JFrame {

    DadosClimaticosPresenter presenter;

    /**
     * Creates new form DadosClima
     */
    public ViewDadosClima() {
//        EstacaoClimatica estacaoClimatica = new EstacaoClimatica();
//        Painel painelClimaObserver = new PainelClimaObserver();
//        Painel estatisticaClimaObserver = new EstatisticaClimaObserver();
//        Painel maximasMinimasObserver = new MaximasMinimasObserver();
//
//        estacaoClimatica.registrarPainel(painelClimaObserver);
//        estacaoClimatica.registrarPainel(estatisticaClimaObserver);
//        estacaoClimatica.registrarPainel(maximasMinimasObserver);
        initComponents();
        this.setLocationRelativeTo(this.getParent());

    }

    public JTable getTblRegistros() {
        return tblRegistros;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        lblNumeroRegistros = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblTemperaturaMedia = new javax.swing.JLabel();
        lblUmidadeMedia = new javax.swing.JLabel();
        lblPressaoMedia = new javax.swing.JLabel();
        lblRegistrosMedia = new javax.swing.JLabel();
        jInternalFrame4 = new javax.swing.JInternalFrame();
        jLabel12 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        cbFormatoLog = new javax.swing.JComboBox<>();
        jInternalFrame5 = new javax.swing.JInternalFrame();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblUmidadeUltimaAtt = new javax.swing.JLabel();
        lblPressaoUltimaAtt = new javax.swing.JLabel();
        lblDataUltimaAtt = new javax.swing.JLabel();
        lblTemperaturaUltimaAtt = new javax.swing.JLabel();
        jInternalFrame6 = new javax.swing.JInternalFrame();
        btnRemover = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRegistros = new javax.swing.JTable();
        jInternalFrame7 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        lblTemperatura = new javax.swing.JLabel();
        lblUmidade = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblPressao = new javax.swing.JLabel();
        btnIncluir = new javax.swing.JButton();
        txtData = new javax.swing.JTextField();
        txtTemperatura = new javax.swing.JTextField();
        txtUmidade = new javax.swing.JTextField();
        txtPresao = new javax.swing.JTextField();
        btnDataAtual = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 850));
        setPreferredSize(new java.awt.Dimension(1500, 850));
        getContentPane().setLayout(null);

        lblNumeroRegistros.setText("99999");
        getContentPane().add(lblNumeroRegistros);
        lblNumeroRegistros.setBounds(1290, 760, 160, 14);

        jLabel2.setText("Número de registros:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1110, 760, 160, 14);

        jInternalFrame3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jInternalFrame3.setResizable(true);
        jInternalFrame3.setTitle("Dados médios");
        jInternalFrame3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInternalFrame3.setOpaque(true);
        jInternalFrame3.setVisible(true);
        jInternalFrame3.getContentPane().setLayout(null);

        jLabel16.setText("Umidade");
        jInternalFrame3.getContentPane().add(jLabel16);
        jLabel16.setBounds(60, 90, 76, 24);

        jLabel17.setText("Pressão");
        jInternalFrame3.getContentPane().add(jLabel17);
        jLabel17.setBounds(60, 130, 76, 24);

        jLabel18.setText("Temperatura");
        jInternalFrame3.getContentPane().add(jLabel18);
        jLabel18.setBounds(60, 50, 76, 24);

        jLabel19.setText("Número de registro");
        jInternalFrame3.getContentPane().add(jLabel19);
        jLabel19.setBounds(60, 180, 116, 24);

        lblTemperaturaMedia.setText("Temperatura");
        jInternalFrame3.getContentPane().add(lblTemperaturaMedia);
        lblTemperaturaMedia.setBounds(200, 50, 129, 24);

        lblUmidadeMedia.setText("Umidade");
        jInternalFrame3.getContentPane().add(lblUmidadeMedia);
        lblUmidadeMedia.setBounds(200, 90, 129, 24);

        lblPressaoMedia.setText("Pressão");
        jInternalFrame3.getContentPane().add(lblPressaoMedia);
        lblPressaoMedia.setBounds(200, 130, 129, 24);

        lblRegistrosMedia.setText("Número de registro");
        jInternalFrame3.getContentPane().add(lblRegistrosMedia);
        lblRegistrosMedia.setBounds(200, 180, 129, 24);

        getContentPane().add(jInternalFrame3);
        jInternalFrame3.setBounds(440, 30, 370, 290);

        jInternalFrame4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jInternalFrame4.setResizable(true);
        jInternalFrame4.setTitle("Configuração do Sistema");
        jInternalFrame4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInternalFrame4.setOpaque(true);
        jInternalFrame4.setVisible(true);
        jInternalFrame4.getContentPane().setLayout(null);

        jLabel12.setText("Log");
        jInternalFrame4.getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 50, 76, 24);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(btnSalvar);
        btnSalvar.setBounds(148, 109, 140, 23);

        cbFormatoLog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XML", "jSON" }));
        cbFormatoLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFormatoLogActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(cbFormatoLog);
        cbFormatoLog.setBounds(132, 52, 156, 20);

        getContentPane().add(jInternalFrame4);
        jInternalFrame4.setBounds(1160, 30, 300, 280);
        jInternalFrame4.getAccessibleContext().setAccessibleName("ConfiguracaoSistema");

        jInternalFrame5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jInternalFrame5.setResizable(true);
        jInternalFrame5.setTitle("Última atualização do tempo");
        jInternalFrame5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInternalFrame5.setOpaque(true);
        jInternalFrame5.setVisible(true);
        jInternalFrame5.getContentPane().setLayout(null);

        jLabel24.setText("Umidade");
        jInternalFrame5.getContentPane().add(jLabel24);
        jLabel24.setBounds(30, 140, 76, 24);

        jLabel25.setText("Pressão");
        jInternalFrame5.getContentPane().add(jLabel25);
        jLabel25.setBounds(30, 180, 76, 24);

        jLabel26.setText("Temperatura");
        jInternalFrame5.getContentPane().add(jLabel26);
        jLabel26.setBounds(30, 100, 76, 24);

        jLabel27.setText("Data");
        jInternalFrame5.getContentPane().add(jLabel27);
        jLabel27.setBounds(30, 220, 116, 24);

        lblUmidadeUltimaAtt.setText("Umidade");
        jInternalFrame5.getContentPane().add(lblUmidadeUltimaAtt);
        lblUmidadeUltimaAtt.setBounds(160, 140, 129, 24);

        lblPressaoUltimaAtt.setText("Pressão");
        jInternalFrame5.getContentPane().add(lblPressaoUltimaAtt);
        lblPressaoUltimaAtt.setBounds(160, 180, 129, 24);

        lblDataUltimaAtt.setText("Data");
        jInternalFrame5.getContentPane().add(lblDataUltimaAtt);
        lblDataUltimaAtt.setBounds(160, 220, 129, 24);

        lblTemperaturaUltimaAtt.setText("Temperatura");
        jInternalFrame5.getContentPane().add(lblTemperaturaUltimaAtt);
        lblTemperaturaUltimaAtt.setBounds(160, 100, 62, 14);

        getContentPane().add(jInternalFrame5);
        jInternalFrame5.setBounds(524, 342, 304, 390);
        jInternalFrame5.getAccessibleContext().setAccessibleName("UltimaAtualizacao");

        jInternalFrame6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jInternalFrame6.setResizable(true);
        jInternalFrame6.setTitle("Registros");
        jInternalFrame6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInternalFrame6.setOpaque(true);
        jInternalFrame6.setVisible(true);
        jInternalFrame6.getContentPane().setLayout(null);

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        jInternalFrame6.getContentPane().add(btnRemover);
        btnRemover.setBounds(290, 310, 170, 23);

        tblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Data", "Temperatura", "Unidade", "Pressão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRegistros);

        jInternalFrame6.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 11, 452, 290);

        getContentPane().add(jInternalFrame6);
        jInternalFrame6.setBounds(24, 342, 474, 390);

        jInternalFrame7.setTitle("Máximas e mínimas");
        jInternalFrame7.setVisible(true);
        jInternalFrame7.getContentPane().setLayout(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jInternalFrame7.getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 590, 350);

        getContentPane().add(jInternalFrame7);
        jInternalFrame7.setBounds(850, 342, 610, 390);
        jInternalFrame7.getAccessibleContext().setAccessibleName("MaxMim");

        jInternalFrame2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jInternalFrame2.setResizable(true);
        jInternalFrame2.setTitle("Dados do tempo");
        jInternalFrame2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInternalFrame2.setOpaque(true);
        jInternalFrame2.setVisible(true);
        jInternalFrame2.getContentPane().setLayout(null);

        lblTemperatura.setText("Temperatura");
        jInternalFrame2.getContentPane().add(lblTemperatura);
        lblTemperatura.setBounds(10, 89, 76, 24);

        lblUmidade.setText("Umidade");
        jInternalFrame2.getContentPane().add(lblUmidade);
        lblUmidade.setBounds(10, 131, 76, 24);

        lblData.setText("Data");
        jInternalFrame2.getContentPane().add(lblData);
        lblData.setBounds(10, 47, 76, 24);

        lblPressao.setText("Presão");
        jInternalFrame2.getContentPane().add(lblPressao);
        lblPressao.setBounds(10, 173, 76, 24);

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(btnIncluir);
        btnIncluir.setBounds(201, 210, 150, 23);

        txtData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtDataMouseExited(evt);
            }
        });
        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(txtData);
        txtData.setBounds(201, 50, 150, 20);

        txtTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperaturaActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(txtTemperatura);
        txtTemperatura.setBounds(200, 90, 151, 20);

        txtUmidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUmidadeActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(txtUmidade);
        txtUmidade.setBounds(200, 130, 151, 20);

        txtPresao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPresaoActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(txtPresao);
        txtPresao.setBounds(200, 170, 151, 20);

        btnDataAtual.setText("Data atual");
        btnDataAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataAtualActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(btnDataAtual);
        btnDataAtual.setBounds(203, 20, 150, 23);

        getContentPane().add(jInternalFrame2);
        jInternalFrame2.setBounds(40, 30, 370, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed

    }//GEN-LAST:event_btnIncluirActionPerformed

    public JButton getBtnIncluir() {
        return btnIncluir;
    }

    public JTextField getTxtData() {
        return txtData;
    }

    public void setLblPressaoMedia(JLabel lblPressaoMedia) {
        this.lblPressaoMedia = lblPressaoMedia;
    }

    public void setLblRegistrosMedia(JLabel lblRegistrosMedia) {
        this.lblRegistrosMedia = lblRegistrosMedia;
    }

    public JLabel getLblDataUltimaAtt() {
        return lblDataUltimaAtt;
    }
    
    public JLabel getLblPressaoUltimaAtt() {
        return lblPressaoUltimaAtt;
    }

    public JLabel getLblTemperaturaUltimaAtt() {
        return lblTemperaturaUltimaAtt;
    }

    public JLabel getLblUmidadeUltimaAtt() {
        return lblUmidadeUltimaAtt;
    }

    public void setLblTemperaturaMedia(JLabel lblTemperaturaMedia) {
        this.lblTemperaturaMedia = lblTemperaturaMedia;
    }

    public void setLblUmidadeMedia(JLabel lblUmidadeMedia) {
        this.lblUmidadeMedia = lblUmidadeMedia;
    }

    public JLabel getLblPressaoMedia() {
        return lblPressaoMedia;
    }

    public JLabel getLblRegistrosMedia() {
        return lblRegistrosMedia;
    }

    public JLabel getLblTemperaturaMedia() {
        return lblTemperaturaMedia;
    }

    public JLabel getLblUmidadeMedia() {
        return lblUmidadeMedia;
    }

    public JLabel getLblNumeroRegistros() {
        return lblNumeroRegistros;
    }

    public JTextField getTxtPresao() {
        return txtPresao;
    }

    public JTextField getTxtTemperatura() {
        return txtTemperatura;
    }

    public JTextField getTxtUmidade() {
        return txtUmidade;
    }

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void txtTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperaturaActionPerformed

    private void txtUmidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUmidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUmidadeActionPerformed

    private void txtPresaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPresaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPresaoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    public JButton getBtnDataAtual() {
        return btnDataAtual;
    }

    public JLabel getLblData() {
        return lblData;
    }

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void txtDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDataMouseExited

    }//GEN-LAST:event_txtDataMouseExited

    private void btnDataAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDataAtualActionPerformed

    private void cbFormatoLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFormatoLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFormatoLogActionPerformed

    public void setTxtData(JTextField txtData) {
        this.txtData = txtData;
    }

    public JButton getBtnRemover() {
        return btnRemover;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDadosClima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDadosClima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDadosClima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDadosClima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDadosClima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDataAtual;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbFormatoLog;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    public javax.swing.JInternalFrame jInternalFrame2;
    public javax.swing.JInternalFrame jInternalFrame3;
    public javax.swing.JInternalFrame jInternalFrame4;
    public javax.swing.JInternalFrame jInternalFrame5;
    public javax.swing.JInternalFrame jInternalFrame6;
    private javax.swing.JInternalFrame jInternalFrame7;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDataUltimaAtt;
    private javax.swing.JLabel lblNumeroRegistros;
    private javax.swing.JLabel lblPressao;
    private javax.swing.JLabel lblPressaoMedia;
    private javax.swing.JLabel lblPressaoUltimaAtt;
    private javax.swing.JLabel lblRegistrosMedia;
    private javax.swing.JLabel lblTemperatura;
    private javax.swing.JLabel lblTemperaturaMedia;
    private javax.swing.JLabel lblTemperaturaUltimaAtt;
    private javax.swing.JLabel lblUmidade;
    private javax.swing.JLabel lblUmidadeMedia;
    private javax.swing.JLabel lblUmidadeUltimaAtt;
    private javax.swing.JTable tblRegistros;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtPresao;
    private javax.swing.JTextField txtTemperatura;
    private javax.swing.JTextField txtUmidade;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnSalvar
     */
    public javax.swing.JButton getBtnSalvar() {
        return btnSalvar;
    }

    /**
     * @return the cbFormatoLog
     */
    public javax.swing.JComboBox<String> getCbFormatoLog() {
        return cbFormatoLog;
    }
}
